on:
  push:
    branches:
      - "aws"

jobs:
  Docker:
    runs-on: ubuntu-latest
    needs: [Tests]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: gabrielgaspar447/tfc_backend:aws

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: gabrielgaspar447/tfc_frontend:aws

  Deploy:
    runs-on: ubuntu-latest
    needs: [Docker]
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ec2-user@ec2-54-233-176-138.sa-east-1.compute.amazonaws.com
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker-compose pull
            docker-compose up


