on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run ESLint check
      run: npx eslint .
      working-directory: ./backend