on: [push, pull_request]

jobs:
  ESLint:
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1

    - name: Change to backend directory
      run: cd backend

    - name: Install dependencies
      run: npm install

    - name: Run ESLint check
      run: npx eslint .